### ISSUE TITLE
几点问题与建议

### ISSUE THREAD

**Issue by YexiangYan** [Hanlin-Dong/SmartAnalyze#1]
很棒的工作，SmartAnalyze也有了python版本。感谢所做的工作。
几点问题与建议：
1）setAlgorithm函数中使用了关键字参数，这是不合适的。因为openseespy内部调用的是opensees的C++库，因此，python在这种接口中是不支持关键字参数的，会报错。
2）python的函数递归虽然简洁，效率不够高，会占用了大量内存和时间。
3）建议不使用 from openseespy.opensees import * 这种写法，会造成命名空间混乱。建议使用  import openseespy.opensees as ops（or op）。
浅见，祝好！

**Comment by Hanlin-Dong** [comment]
感谢！我个人暂不使用python版，欢迎Pull Request，大家一起完善。
