### ISSUE TITLE
Undefined Variable getCTestNorms

### ISSUE THREAD

**Issue by AmyMcCall** [Hanlin-Dong/SmartAnalyze#2]
Hanlin,

Thank you for making SmartAnalyze available. I am running this function in a THA and am getting stuck at line 436 in the RecursiveAnalyze function. norm is being set equal to a variable called "getCTestNorms". I cannot find the definition for this anywhere in SmartAnalyze and can't get past this point. 

Can you help me with this? Thanks,

Amy

**Comment by Hanlin-Dong** [comment]
Hi Amy, 

I checked the documentation, and the `getCTestNorms()` command should have been changed to `testNorm()` command. The documentation is here: https://openseespydoc.readthedocs.io/en/latest/src/testNorm.html?highlight=testnorms .
Would you please try to change  `getCTestNorms()`  to  `testNorm()` in the source code and make a test? Please let me know the result. Thanks.

Hanlin

**Comment by AmyMcCall** [comment]
Hanlin,

Thank you for your quick response. That worked for me.

Thanks again,

Amy
